# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_USER: Bubbleioa
  GIT_EMAIL: 1342130847@qq.com
  SRC_REPO: Bubbleioa/Mirai
  SRC_BRANCH: main
  DEPLOY_REPO: Bubbleioa/Mirai-built
  DEPLOY_BRANCH: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: test
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        run: |
          echo $DEPLOY_KEY
          echo "$DEPLOY_KEY"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout src repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.SRC_REPO }}
          ref: ${{ env.SRC_BRANCH }}

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git
          
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install dependencies
        run: |
          npm install

      - name: build
        run: |
          npm run build
      
      - name: deploy
        run: |
          echo "$DEPLOY_KEY"
          cp -R ./public/* .deploy_git/
          cd .deploy_git
          git add -A
          git commit -m 'Github Action'
          git push
